# -*- coding: utf-8 -*-

{
    "name": 'ARO V9',
    "version": "0.1",
    "depends": [
        'base',
        'account',
        'product',
        'sale',
    ],
    "author": "Rakotomalala Haritiana Maminiaina <haryoran04@gmail.com>",
    "category": "Insurances",
    "installable": True,
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/insurance_subscription_type_data.xml',
        'data/aro_branche_assurance.xml',
        'data/aro_fraction_data.xml',
        'data/aro_produit_assurance.xml',
        'data/aro_type_risque.xml',
        'data/aro_type_risque_description.xml',
        'data/aro_type_risque_clause.xml',
        'views/menu.xml',
        'views/aro_commission_view.xml',
        'views/aro_branche_assurance_view.xml',
        'views/aro_produit_assurance_view.xml',
        'views/aro_fraction_assurance_view.xml',
        'views/aro_type_risque_view.xml',
        'views/aro_trs_clause_view.xml',
        'views/aro_trs_description_view.xml',
        'data/product_template_data.xml',
        'views/product_template_view.xml',
        'views/aro_taxe_view.xml',
        'views/aro_type_apporteur_view.xml',
        'views/aro_registration_fee_view.xml',
        'data/aro_type_apporteur_data.xml',
        'data/aro_type_emission_data.xml',
        'views/aro_type_emission_view.xml',
        'views/aro_amendment_line_view.xml',
        'views/insurance_subscription_type_view.xml',
        'views/aro_insurance_subscription_view.xml',
        'views/aro_status_view.xml',
        'data/aro_status_data.xml',
        'views/menu_subscription_branch.xml',
        'views/type_risk_warranty_template_view.xml',
        'views/account_invoice_view.xml',
        'views/res_partner_family_view.xml',
        'views/res_partner_view.xml',
    ],
}
